# From: https://github.com/cwtools/cwtools-action

name: CWTools CI

on: [pull_request, push] # other events may work but are not supported

jobs:
  cwtools_job:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1 # required
    - uses: cwtools/cwtools-action@v1.1.0
      with:
        game: eu4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required, secret is automatically set by github
