# From: https://github.com/cwtools/cwtools-action
# Run on ubuntu-latest as docker runners aren't officially supported and it's causing issues.

name: CWTools CI

on: [workflow_call] # other events may work but are not supported

jobs:
  cwtools_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 # required
    - uses: cwtools/cwtools-action@v1.1.0
      with:
        game: eu4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required, secret is automatically set by github
